# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  edgehead:
    builders:
#      built_value_generator|built_value:
#        enabled: false
      egamebook_builder|writers_builder:
        generate_for: ['lib/writers_input.dart']
