name: edgehead
version: 2.0.0
description: A game of fractal stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  built_collection: any
  built_value: any
  cli_menu: any
  egamebook_builder:
    path: ../egamebook_builder
  meta: any
  logging: any
  path: any
  quiver: any
  slot_machine: any

dependency_overrides:
  analyzer_plugin: ^0.0.1-alpha.4

dev_dependencies:
  args: any
  build_runner: any
  built_value_generator: any
  source_gen: any
  test: any
