name: edgehead
version: 2.0.0-dev.1
description: A game of fractal stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=1.24.3 <3.0.0'

dependencies:
  built_collection: any
  built_value: any
  cli_menu: any
  meta: any
  logging: any
  path: any
  quiver: any
  slot_machine: any

dev_dependencies:
  args: any
  build_runner: any
  built_value_generator: any
  code_builder: any
  recase: any
  source_gen: any
  test: any
